update.

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -14,11 +14,11 @@ jobs:
           fetch-depth: 0
       - run: |
           tag=$(git describe --abbrev=0 --tags 2>/dev/null)
-          if [ $? -ne 0 ]; then
-            echo "::error $ERROR_MESSAGE"
-          else
-            echo "current_tag=$tag" >> "$GITHUB_OUTPUT"
-          fi
+          # if [ $? -ne 0 ]; then
+          #   echo "::error $ERROR_MESSAGE"
+          # else
+          #   echo "current_tag=$tag" >> "$GITHUB_OUTPUT"
+          # fi
         id: check-tag
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -43,26 +43,26 @@ jobs:
   #         echo $pr_labels
   #       env:
   #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  build-changelog:
-    runs-on: ubuntu-latest
-    needs: check-first-release
-    steps:
-      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
-        with:
-          fetch-depth: 0
-      - run: |
-          git rev-list --tags --skip=0 --max-count=1
-          git describe --abbrev=0 --tags
-      - name: Build Changelog
-        id: github_release
-        uses: mikepenz/release-changelog-builder-action@v4.0.0-b02
-        with:
-          fromTag: ${{needs.check-first-release.outputs.current_tag}}
-          toTag: ${{ github.ref }}
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      - run: |
-          echo ${{steps.github_release.outputs.changelog}}
+  # build-changelog:
+  #   runs-on: ubuntu-latest
+  #   needs: check-first-release
+  #   steps:
+  #     - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
+  #       with:
+  #         fetch-depth: 0
+  #     - run: |
+  #         git rev-list --tags --skip=0 --max-count=1
+  #         git describe --abbrev=0 --tags
+  #     - name: Build Changelog
+  #       id: github_release
+  #       uses: mikepenz/release-changelog-builder-action@v4.0.0-b02
+  #       with:
+  #         fromTag: ${{needs.check-first-release.outputs.current_tag}}
+  #         toTag: ${{ github.ref }}
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #     - run: |
+  #         echo ${{steps.github_release.outputs.changelog}}
   # bump-version:
   #   runs-on: ubuntu-latest
   #   permissions: {}
